### PR TITLE
Add options necessary to run on Java 16+

### PR DESCRIPTION
**Pull request by golinski**

### CODE REVIEW

**Comment by GastonGonzalez** [comment]
Confirmed that this PR still works correctly with JDK 11.

```
$ java -version
java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
```

I'll retest and run a regression with JDK 17, shortly.

**Comment by GastonGonzalez** [comment]
Tested install using Oracle Java JDK 17.

```
$ java -version
java version "17" 2021-09-14 LTS
Java(TM) SE Runtime Environment (build 17+35-LTS-2724)
Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)
```

The installation using percli seems to work correctly. However, following a login into Peregrine via a web browser the following message is displayed in the console:

```
ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.9.1
ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.9.1
ANTLR Tool version 4.7.1 used for code generation does not match the current runtime version 4.9.1
ANTLR Runtime version 4.7.1 used for parser compilation does not match the current runtime version 4.9.1
```

@golinski - Can you look into this?

**Comment by GastonGonzalez** [comment]
@golinski - I spoke to @reusr1. The ANTLR issue doesn't seem to be a problem that should block this. I'm in the process of incrementing the release, merging this PR and will push to this to NPM.

**Comment by golinski** [comment]
The ANTLR error seems to be present in both Java 11 and java 17. As far as I can tell, the only bundle using ANTLR is `Apache Sling Scripting HTL Compiler (org.apache.sling.scripting.sightly.compiler)`. Its POM says that 4.7.1 is used at compilation and it would be best to supply this version at runtime (per the message). BTW, AEM-SDK carries version 4.7.1.

**Pull request merged**
